version: "2"
services:
  web:
    build:
      context: .
    container_name: app
    volumes:
      - ".:/home/alpine/app"
      - "/home/alpine/app/node_modules"
    image: "app:development"
    environment:
      NODE_ENV: "development"
    ports:
      - "3000:3000"
      - "5858:5858"
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - "./data/mongo:/data/db"
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: local_redis
    volumes:
      - "./data/redis:/data/redis"
    ports:
      - "6379:6379"